### PR TITLE
feat: pin address links in rootstore on opening

### PR DESCRIPTION
**Pull request by zachferland**

### CODE REVIEW

**Comment by oed** [comment]
I assume this has been tested locally?

**Comment by oed** [comment]
This made me think. We should probably do the same each time we open the root-store in 3box-js?

**Comment by zachferland** [comment]
oh forgot to follow up on this last week, pretty sure tested when PR first opened, but gonna try one more time locally today before merging

**Comment by zachferland** [comment]
Doubled checked, all set, merging

**Pull request merged**
