### PR TITLE
chore: up ipfs 0.46.0

### PR DESCRIPTION
**Pull request by zachferland**

### CODE REVIEW

**Comment by zachferland** [comment]
Not seeing any s3-datastore issues, ran locally with out issues, but see tests failing here.

**Comment by oed** [comment]
@zachferland you made sure that data from the previous version is possible to pick up from this version I assume?

**Comment by zachferland** [comment]
at least locally, yeah had some data prior, but will confirm 

what issues had you seen? just a errors thrown 

there may be a data migration for the datastore (but not blockstore or anything), going to look into it

**Comment by achingbrain** [comment]
The breakage here was caused by an `Error` emitted by `fs.readFile` failing an `instanceof Error` check elsewhere in the codebase due to how Jest isolates tests from each other.

It's fixed in `err-code@2.0.3` so please remove any `node_modules` caches and run CI again.

**Comment by oed** [comment]
Thanks for looking at this and solving the issue @achingbrain!

**Comment by achingbrain** [comment]
No problem, happy to help!

**Pull request merged**
