### PR TITLE
Release/1.6.0

### PR DESCRIPTION
**Pull request by oed**

### CODE REVIEW

**Comment by zachferland** [comment]
Bug Fix - https://github.com/3box/3box-pinning-node/pull/180

general testing with new node/address server and current js lib (with bug fix) (including api calls)
general testing with new node/address server and js lib release 
tested getConfig

**Comment by oed** [comment]
Merged #180 and rebased this branch.

**Comment by oed** [comment]
@zachferland should we merge 178 before this as well?

**Comment by zachferland** [comment]
@oed  yes ideally, but have to fix tests there, think just mocks, so hopefully squeeze some time in for that

**Pull request merged**
